### ISSUE TITLE
Add configuration for Travis-CI

### ISSUE THREAD

**Issue by longtimeago** [maven-download-plugin/maven-download-plugin#64]
https://travis-ci.com/
This will allow us to know if the PR is compilable and passed tests

It's really easy to do - just add `.travis.yml` to the project root with following content:
```yaml
language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=256m -Xmx512m"
    - JAVA_OPTS="-XX:MaxPermSize=256m -Xmx512m"
jdk:
  - oraclejdk7
  - openjdk7
script:
  - mvn clean install -Pits --batch-mode --errors
```
